## Particle Gun Macro for edep-sim

## Physics changes

## Not everything is LAr
/edep/phys/ionizationModel 0

# This ensures that each hit segment in the LAr is only associated with one
# trajectory. It must be run BEFORE /edep/update.
/edep/hitSeparation volTPCActive -1 mm

/edep/update

/generator/count/fixed/number 40
/generator/count/set fixed

/generator/time/uniform/tmax 40000 ns
/generator/time/uniform/tmin 0 ns
/generator/time/set uniform 



# print commands
/gps/verbose 1

# generate particles
/gps/particle neutron

/gps/direction -1.0 0.0 0.0 

# next, we generate a flat distribution with each muon between $ARCUBE_ENERGY_MINIMUM and $ARCUBE_ENERGY_MAXIMUM (Gradient of 0 means flat and )
/gps/ene/type Lin
/gps/ene/min 12 MeV
/gps/ene/max 14 MeV
/gps/ene/gradient 0
/gps/ene/intercept 1 

# Specify the volume where we want the muons to be produced in. THIS MAY NEED TO BE CHANGED WHEN GDML CHANGES TOO!

/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 3 cm 
/gps/pos/centre 1.5 -0.2 0.3 m


# /gps/pos/sigma_r 0.5 cm

#/gps/pos/type Point

#/gps/pos/halfx 3.5 m 
#/gps/pos/halfy 2.0 m 
#/gps/pos/halfz 3.0 m

#/gps/ang/type cos # Not fully convinced this should be cosine law 
#/gps/ang/maxtheta 90 deg # Remember this is 0-90 deg and the rotating it by phi 0-360 deg gives a hemisphere pointing in beam direction
#/gps/ang/rot1 1 0 0
#/gps/ang/rot2 0 -1 0

/edep/db/set/requireEventsWithHits true
